const ContactData = [
  {
    id: 1,
    name: "Olusanya Agbesanya",
    profilePicture: "https://randomuser.me/api/portraits/men/1.jpg",
    tags: ["Friends", "Favorites"],
    jobTitle: "Frontend Developer",
    company: "Freelancer",
    isFavorite: true,
  },
  {
    id: 2,
    name: "Jane Smith",
    profilePicture: "https://randomuser.me/api/portraits/women/2.jpg",
    tags: ["Family"],
    jobTitle: "Graphic Designer",
    company: "Adobe",
    isFavorite: false,
  },
  {
    id: 3,
    name: "David Johnson",
    profilePicture: "https://randomuser.me/api/portraits/men/3.jpg",
    tags: ["Close Friends", "Favorites"],
    jobTitle: "Backend Engineer",
    company: "Amazon",
    isFavorite: true,
  },
  {
    id: 4,
    name: "Emily White",
    profilePicture: "https://randomuser.me/api/portraits/women/4.jpg",
    tags: ["Emergency"],
    jobTitle: "Doctor",
    company: "General Hospital",
    isFavorite: false,
  },
  {
    id: 5,
    name: "Michael Brown",
    profilePicture: "https://randomuser.me/api/portraits/men/5.jpg",
    tags: ["Friends", "Family"],
    jobTitle: "Data Scientist",
    company: "Google",
    isFavorite: true,
  },
  {
    id: 6,
    name: "Sophia Wilson",
    profilePicture: "https://randomuser.me/api/portraits/women/6.jpg",
    tags: ["Favorites"],
    jobTitle: "UX Designer",
    company: "Meta",
    isFavorite: true,
  },
  {
    id: 7,
    name: "Daniel Martinez",
    profilePicture: "https://randomuser.me/api/portraits/men/7.jpg",
    tags: ["Close Friends"],
    jobTitle: "Software Engineer",
    company: "Netflix",
    isFavorite: false,
  },
  {
    id: 8,
    name: "Olivia Taylor",
    profilePicture: "https://randomuser.me/api/portraits/women/8.jpg",
    tags: ["Family", "Emergency"],
    jobTitle: "HR Manager",
    company: "Tesla",
    isFavorite: false,
  },
  {
    id: 9,
    name: "James Anderson",
    profilePicture: "https://randomuser.me/api/portraits/men/9.jpg",
    tags: ["Friends"],
    jobTitle: "Cybersecurity Analyst",
    company: "Microsoft",
    isFavorite: false,
  },
  {
    id: 10,
    name: "Ava Thomas",
    profilePicture: "https://randomuser.me/api/portraits/women/10.jpg",
    tags: ["Favorites", "Close Friends"],
    jobTitle: "Marketing Specialist",
    company: "Apple",
    isFavorite: true,
  },
];

export default ContactData;
